name: Linux Maven Wrapper Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Linux Java ${{ matrix.java }} Maven Wrapper
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Set executable permission for mvnw
        run: chmod +x ./mvnw
      - name: Build Project
        run: ./mvnw -B -C -V -ntp clean install
